version: '3.8'
services:
    web:
        build:
            context: ./
            target: runner
        volumes:
            - .:/app
            - /app/node_modules # <-- creates the node_modules in frontend path
            - /app/.next # <-- creates the .next folder in frontend path
        command: npm run dev
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: development
